"""
Yanfaa Professional Scraper - Simplified Version
2 Pages Only: Credentials & Scraping
"""
import streamlit as st
import json
import asyncio
import sys
import os
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional
import pandas as pd
from urllib.parse import urlparse

# Fix Windows asyncio issue with subprocess
if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

from auth import YanfaaAuth
from scraper import YanfaaScraper
import config

# ============================================================================
# Cookie Converter Class
# ============================================================================

class CookieConverter:
    """Cookie format converter"""
    
    def json_to_netscape(self, cookies: Dict, domain: str = "") -> str:
        """Convert cookies from JSON to Netscape format"""
        lines = [
            "# Netscape HTTP Cookie File",
            "# Generated by Yanfaa Professional Scraper",
            f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            ""
        ]
        
        if domain:
            parsed = urlparse(domain)
            domain = parsed.netloc or parsed.path
            if domain.startswith('www.'):
                domain = domain[4:]
        
        expiration = "2147483647"
        
        if isinstance(cookies, dict):
            for name, value in cookies.items():
                if isinstance(value, dict):
                    cookie_domain = value.get('domain', domain)
                    cookie_path = value.get('path', '/')
                    cookie_secure = "TRUE" if value.get('secure', False) else "FALSE"
                    cookie_expiration = str(value.get('expiration', expiration))
                    cookie_name = value.get('name', name)
                    cookie_value = value.get('value', str(value))
                else:
                    cookie_domain = f".{domain}" if domain else ""
                    cookie_path = "/"
                    cookie_secure = "FALSE"
                    cookie_expiration = expiration
                    cookie_name = name
                    cookie_value = str(value)
                
                line = f"{cookie_domain}\tTRUE\t{cookie_path}\t{cookie_secure}\t{cookie_expiration}\t{cookie_name}\t{cookie_value}"
                lines.append(line)
        
        return "\n".join(lines)
    
    def netscape_to_json(self, netscape_content: str) -> Dict:
        """Convert cookies from Netscape to JSON format"""
        cookies = {}
        lines = netscape_content.split('\n')
        
        for line in lines:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            
            parts = line.split('\t')
            if len(parts) >= 7:
                domain, flag, path, secure, expiration, name, value = parts[:7]
                cookies[name] = {
                    "domain": domain,
                    "path": path,
                    "secure": secure.lower() == "true",
                    "expiration": int(expiration) if expiration.isdigit() else None,
                    "value": value
                }
        
        return cookies

# ============================================================================
# Credentials Manager Class
# ============================================================================

class CredentialsManager:
    """Manage credentials"""
    
    def __init__(self, credentials_file: str = None):
        self.credentials_file = Path(credentials_file) if credentials_file else config.BASE_DIR / "credentials.json"
        self.credentials: Dict = {}
        self.load_credentials()
    
    def load_credentials(self):
        """Load credentials from file"""
        try:
            if self.credentials_file.exists():
                with open(self.credentials_file, 'r', encoding='utf-8') as f:
                    self.credentials = json.load(f)
            else:
                self.credentials = {}
        except Exception as e:
            print(f"Error loading credentials: {str(e)}")
            self.credentials = {}
    
    def save_credentials(self):
        """Save credentials to file"""
        try:
            with open(self.credentials_file, 'w', encoding='utf-8') as f:
                json.dump(self.credentials, f, indent=2, ensure_ascii=False)
            return True
        except Exception as e:
            print(f"Error saving credentials: {str(e)}")
            return False
    
    def add_credential(self, name: str, username: str, password: str, 
                      base_url: str = "", login_url: str = ""):
        """Add new credential"""
        if name in self.credentials:
            raise ValueError(f"Credential '{name}' already exists")
        
        self.credentials[name] = {
            "name": name,
            "username": username,
            "email": username,
            "password": password,
            "base_url": base_url,
            "login_url": login_url,
            "created_at": datetime.now().isoformat()
        }
        return self.save_credentials()
    
    def get_credential(self, name: str) -> Optional[Dict]:
        """Get specific credential"""
        return self.credentials.get(name)
    
    def get_all_credentials(self) -> List[Dict]:
        """Get all credentials"""
        return list(self.credentials.values())
    
    def delete_credential(self, name: str) -> bool:
        """Delete credential"""
        if name in self.credentials:
            del self.credentials[name]
            return self.save_credentials()
        return False

# ============================================================================
# Streamlit Configuration
# ============================================================================

st.set_page_config(
    page_title="Yanfaa Professional Scraper",
    page_icon="🕷️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Professional CSS
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
    
    * {
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    }
    
    .main-header {
        font-size: 3.5rem;
        font-weight: 700;
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        text-align: center;
        margin-bottom: 2rem;
        padding: 1rem;
        letter-spacing: -0.02em;
    }
    
    .stButton>button {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        border: none;
        border-radius: 12px;
        padding: 0.75rem 2rem;
        font-weight: 600;
        transition: all 0.3s ease;
        box-shadow: 0 4px 6px rgba(102, 126, 234, 0.2);
    }
    
    .stButton>button:hover {
        transform: translateY(-2px);
        box-shadow: 0 8px 15px rgba(102, 126, 234, 0.4);
    }
    
    .page-header {
        font-size: 2.5rem;
        font-weight: 700;
        color: #667eea;
        margin-bottom: 2rem;
        padding-bottom: 1rem;
        border-bottom: 3px solid #667eea;
        letter-spacing: -0.01em;
    }
</style>
""", unsafe_allow_html=True)

# Initialize components
def init_components():
    return CredentialsManager(), CookieConverter()

credentials_manager, cookie_converter = init_components()

# ============================================================================
# Main Header
# ============================================================================

st.markdown('<h1 class="main-header">🕷️ Yanfaa Professional Scraper</h1>', unsafe_allow_html=True)

# ============================================================================
# Sidebar Navigation
# ============================================================================

st.sidebar.title("🧭 Navigation")
st.sidebar.markdown("---")

page = st.sidebar.radio(
    "Select Page:",
    ["🔐 Credentials", "🕷️ Scrape All Courses"],
    label_visibility="collapsed"
)

# ============================================================================
# Page 1: Credentials
# ============================================================================

if page == "🔐 Credentials":
    st.markdown('<div class="page-header">🔐 Credentials & Cookies Management</div>', unsafe_allow_html=True)
    
    # Credential Selection/Management
    credentials = credentials_manager.get_all_credentials()
    
    if credentials:
        credential_names = [c['name'] for c in credentials]
        selected_cred = st.selectbox("Select Credential:", credential_names, key="cred_select")
        credential = credentials_manager.get_credential(selected_cred)
        
        col1, col2 = st.columns([3, 1])
        with col1:
            st.info(f"**Username:** {credential.get('username', 'N/A')} | **Base URL:** {credential.get('base_url', 'N/A')}")
        with col2:
            if st.button("🗑️ Delete", use_container_width=True):
                if credentials_manager.delete_credential(selected_cred):
                    cookies_file = config.BASE_DIR / f"cookies_{selected_cred}.json"
                    if cookies_file.exists():
                        cookies_file.unlink()
                    st.success(f"✅ Deleted '{selected_cred}'")
                    st.rerun()
    else:
        selected_cred = None
        st.info("No credentials found. Create a new one below.")
    
    st.markdown("---")
    
    # Add/Edit Credential
    with st.expander("➕ Add New Credential", expanded=not credentials):
        with st.form("add_credential_form", clear_on_submit=True):
            col1, col2 = st.columns(2)
            with col1:
                cred_name = st.text_input("Credential Name *", placeholder="e.g., my_account")
                cred_username = st.text_input("Username/Email *", placeholder="user@example.com")
            with col2:
                cred_password = st.text_input("Password *", type="password")
                cred_base_url = st.text_input("Base URL", value="https://yanfaa.com")
            
            cred_login_url = st.text_input("Login URL", value="https://yanfaa.com/us/login")
            
            if st.form_submit_button("➕ Add Credential", use_container_width=True, type="primary"):
                if cred_name and cred_username and cred_password:
                    try:
                        credentials_manager.add_credential(
                            name=cred_name,
                            username=cred_username,
                            password=cred_password,
                            base_url=cred_base_url,
                            login_url=cred_login_url
                        )
                        st.success(f"✅ Credential '{cred_name}' added!")
                        st.rerun()
                    except Exception as e:
                        st.error(f"❌ Error: {str(e)}")
                else:
                    st.warning("⚠️ Please fill all required fields")
    
    if selected_cred:
        cookies_file = config.BASE_DIR / f"cookies_{selected_cred}.json"
        
        # ============================================================================
        # Session Status Indicator (Enhanced)
        # ============================================================================
        st.markdown("---")
        st.markdown("### 📊 Session Status")
        
        # Session status card with visual indicator
        if cookies_file.exists():
            try:
                with open(cookies_file, 'r', encoding='utf-8') as f:
                    current_cookies = json.load(f)
                
                expiration_dates = []
                for cookie_name, cookie_data in current_cookies.items():
                    if isinstance(cookie_data, dict):
                        exp = cookie_data.get('expiration')
                        if exp and isinstance(exp, (int, float)):
                            expiration_dates.append(exp)
                
                # Display session status with cards
                col1, col2, col3 = st.columns(3)
                
                with col1:
                    st.metric("🍪 Total Cookies", len(current_cookies))
                
                if expiration_dates:
                    earliest_exp = min(expiration_dates)
                    exp_datetime = datetime.fromtimestamp(earliest_exp)
                    now = datetime.now()
                    
                    with col2:
                        if exp_datetime > now:
                            time_until_exp = exp_datetime - now
                            days_until_exp = time_until_exp.days
                            hours_until_exp = time_until_exp.seconds // 3600
                            minutes_until_exp = (time_until_exp.seconds % 3600) // 60
                            
                            if days_until_exp > 0:
                                st.metric("⏳ Expires In", f"{days_until_exp}d {hours_until_exp}h")
                            else:
                                st.metric("⏳ Expires In", f"{hours_until_exp}h {minutes_until_exp}m")
                        else:
                            st.metric("⏳ Expired", "Session Expired!")
                    
                    with col3:
                        st.metric("📅 Expiration Date", exp_datetime.strftime('%Y-%m-%d %H:%M'))
                    
                    # Status message
                    if exp_datetime > now:
                        if days_until_exp > 7:
                            st.success(f"✅ **LOGIN SUCCESSFUL - SESSION ACTIVE** | Expires: {exp_datetime.strftime('%Y-%m-%d %H:%M')} ({days_until_exp} days remaining)")
                        elif days_until_exp > 1:
                            st.warning(f"⚠️ **SESSION EXPIRING SOON** | Expires: {exp_datetime.strftime('%Y-%m-%d %H:%M')} ({days_until_exp} days, {hours_until_exp} hours remaining)")
                        else:
                            st.error(f"🔴 **SESSION EXPIRING TODAY** | Expires: {exp_datetime.strftime('%Y-%m-%d %H:%M')} ({hours_until_exp} hours remaining) - **Re-authenticate soon!**")
                    else:
                        st.error(f"❌ **SESSION EXPIRED** | Expired: {exp_datetime.strftime('%Y-%m-%d %H:%M')} - **Please re-authenticate!**")
                else:
                    with col2:
                        st.metric("⏳ Expiration", "No expiry date")
                    with col3:
                        st.metric("📅 Status", "Session cookie")
                    st.info(f"ℹ️ **SESSION ACTIVE** - {len(current_cookies)} cookies (no expiration date set)")
            except Exception as e:
                st.error(f"⚠️ Error reading session file: {str(e)}")
        else:
            col1, col2, col3 = st.columns(3)
            with col1:
                st.metric("🍪 Total Cookies", "0")
            with col2:
                st.metric("⏳ Expires In", "N/A")
            with col3:
                st.metric("📅 Status", "No Session")
            st.warning("⚠️ **NO ACTIVE SESSION** - Please login to create a session")
        
        st.markdown("---")
        
        # ============================================================================
        # Login Options (Cookies Only)
        # ============================================================================
        st.markdown("### 🍪 Login with Cookies")
        
        login_method = st.radio(
            "Choose Cookie Format:",
            [
                "📋 Paste Netscape Cookies",
                "📋 Paste JSON Cookies",
                "📄 Upload JSON Cookies File"
            ],
            horizontal=True
        )
        
        # ============================================================================
        # Method 1: Paste Netscape Cookies
        # ============================================================================
        if login_method == "📋 Paste Netscape Cookies":
            st.info("Paste cookies in Netscape format (from browser extensions like 'cookies.txt' or 'EditThisCookie')")
            
            cookies_text = st.text_area(
                "Paste Netscape Cookies:",
                height=350,
                placeholder="""# Netscape HTTP Cookie File
# https://curl.haxx.se/rfc/cookie_spec.html
# This is a generated file! Do not edit.

.yanfaa.com	TRUE	/	FALSE	1764923098	_gid	GA1.2.703803445.1764832602
.yanfaa.com	TRUE	/	FALSE	1796368602	_clck	1gngwgq%5E2%5Eg1k%5E0%5E2164
.yanfaa.com	TRUE	/	FALSE	1799047002	_scid	Jrcvn-HKSHj595lGlenD6frM6xHWMPZS""",
                help="Paste your complete Netscape cookie file here",
                key="netscape_input"
            )
            
            if st.button("🍪 Login with Cookies", use_container_width=True, type="primary"):
                if cookies_text:
                    try:
                        cookies_json = cookie_converter.netscape_to_json(cookies_text)
                        
                        with open(cookies_file, 'w', encoding='utf-8') as f:
                            json.dump(cookies_json, f, indent=2, ensure_ascii=False)
                        
                        # Show expiration info
                        expiration_dates = []
                        for cookie_name, cookie_data in cookies_json.items():
                            if isinstance(cookie_data, dict):
                                exp = cookie_data.get('expiration')
                                if exp and isinstance(exp, (int, float)):
                                    expiration_dates.append(exp)
                        
                        if expiration_dates:
                            earliest_exp = min(expiration_dates)
                            exp_datetime = datetime.fromtimestamp(earliest_exp)
                            now = datetime.now()
                            
                            if exp_datetime > now:
                                days_until_exp = (exp_datetime - now).days
                                st.success(f"✅ Login successful! Saved {len(cookies_json)} cookies - Expires: {exp_datetime.strftime('%Y-%m-%d %H:%M')} ({days_until_exp} days)")
                            else:
                                st.error(f"❌ Cookies expired! Expired: {exp_datetime.strftime('%Y-%m-%d %H:%M')}")
                        else:
                            st.success(f"✅ Login successful! Saved {len(cookies_json)} cookies")
                        
                        st.balloons()
                        st.rerun()
                    except Exception as e:
                        st.error(f"❌ Error: {str(e)}")
                        import traceback
                        with st.expander("Error Details"):
                            st.code(traceback.format_exc())
                else:
                    st.warning("⚠️ Please paste cookies first")
        
        # ============================================================================
        # Method 2: Paste JSON Cookies
        # ============================================================================
        elif login_method == "📋 Paste JSON Cookies":
            st.info("Paste cookies in JSON format (array or object)")
            
            cookies_text = st.text_area(
                "Paste JSON Cookies:",
                height=350,
                placeholder='''{
  "_gid": {
    "value": "GA1.2.703803445.1764832602",
    "domain": ".yanfaa.com",
    "path": "/",
    "expiration": 1764923098
  },
  "_clck": {
    "value": "1gngwgq%5E2%5Eg1k%5E0%5E2164",
    "domain": ".yanfaa.com",
    "path": "/",
    "expiration": 1796368602
  }
}''',
                help="Paste your cookies in JSON format",
                key="json_input"
            )
            
            if st.button("🍪 Login with Cookies", use_container_width=True, type="primary"):
                if cookies_text:
                    try:
                        cookies_json = json.loads(cookies_text)
                        
                        # Convert if it's an array
                        if isinstance(cookies_json, list):
                            cookies_dict = {}
                            for cookie in cookies_json:
                                if isinstance(cookie, dict) and 'name' in cookie:
                                    cookies_dict[cookie['name']] = {
                                        'value': cookie.get('value', ''),
                                        'domain': cookie.get('domain', '.yanfaa.com'),
                                        'path': cookie.get('path', '/'),
                                        'secure': cookie.get('secure', False),
                                        'expiration': cookie.get('expirationDate', cookie.get('expires', None))
                                    }
                            cookies_json = cookies_dict
                        
                        with open(cookies_file, 'w', encoding='utf-8') as f:
                            json.dump(cookies_json, f, indent=2, ensure_ascii=False)
                        
                        # Show expiration info
                        expiration_dates = []
                        for cookie_name, cookie_data in cookies_json.items():
                            if isinstance(cookie_data, dict):
                                exp = cookie_data.get('expiration')
                                if exp and isinstance(exp, (int, float)):
                                    expiration_dates.append(exp)
                        
                        if expiration_dates:
                            earliest_exp = min(expiration_dates)
                            exp_datetime = datetime.fromtimestamp(earliest_exp)
                            now = datetime.now()
                            
                            if exp_datetime > now:
                                days_until_exp = (exp_datetime - now).days
                                st.success(f"✅ Login successful! Saved {len(cookies_json)} cookies - Expires: {exp_datetime.strftime('%Y-%m-%d %H:%M')} ({days_until_exp} days)")
                            else:
                                st.error(f"❌ Cookies expired! Expired: {exp_datetime.strftime('%Y-%m-%d %H:%M')}")
                        else:
                            st.success(f"✅ Login successful! Saved {len(cookies_json)} cookies")
                        
                        st.balloons()
                        st.rerun()
                    except json.JSONDecodeError as e:
                        st.error(f"❌ Invalid JSON: {str(e)}")
                    except Exception as e:
                        st.error(f"❌ Error: {str(e)}")
                else:
                    st.warning("⚠️ Please paste cookies first")
        
        # ============================================================================
        # Method 3: Upload JSON Cookies File
        # ============================================================================
        elif login_method == "📄 Upload JSON Cookies File":
            st.info("Upload a JSON file containing your cookies.")
            
            uploaded_file = st.file_uploader(
                "Choose a JSON cookies file",
                type=['json'],
                help="Upload a .json file containing cookies exported from browser or other tools"
            )
            
            if uploaded_file is not None:
                try:
                    cookies_content = uploaded_file.read().decode('utf-8')
                    cookies_json = json.loads(cookies_content)
                    
                    st.success(f"✅ File loaded: {len(cookies_json) if isinstance(cookies_json, dict) else len(cookies_json)} cookies found")
                    
                    # Preview cookies
                    with st.expander("Preview Cookies"):
                        st.json(cookies_json)
                    
                    if st.button("🍪 Login with Cookies", use_container_width=True, type="primary"):
                        # Convert if needed (handle different JSON formats)
                        if isinstance(cookies_json, list):
                            # Convert list format to dict
                            cookies_dict = {}
                            for cookie in cookies_json:
                                if isinstance(cookie, dict) and 'name' in cookie:
                                    cookies_dict[cookie['name']] = {
                                        'value': cookie.get('value', ''),
                                        'domain': cookie.get('domain', '.yanfaa.com'),
                                        'path': cookie.get('path', '/'),
                                        'secure': cookie.get('secure', False),
                                        'expiration': cookie.get('expirationDate', cookie.get('expires', None))
                                    }
                            cookies_json = cookies_dict
                        
                        with open(cookies_file, 'w', encoding='utf-8') as f:
                            json.dump(cookies_json, f, indent=2, ensure_ascii=False)
                        
                        st.success(f"✅ Login successful! Saved {len(cookies_json)} cookies")
                        st.balloons()
                        st.rerun()
                
                except json.JSONDecodeError as e:
                    st.error(f"❌ Invalid JSON file: {str(e)}")
                except Exception as e:
                    st.error(f"❌ Error processing file: {str(e)}")

# ============================================================================
# Page 2: Scrape All Courses
# ============================================================================

elif page == "🕷️ Scrape All Courses":
    st.markdown('<div class="page-header">🕷️ Scrape All Courses</div>', unsafe_allow_html=True)
    
    credentials = credentials_manager.get_all_credentials()
    if not credentials:
        st.warning("⚠️ No credentials found. Please add credentials first from 'Credentials' page.")
        st.stop()
    
    credential_names = [c['name'] for c in credentials]
    selected_cred = st.selectbox("🔑 Select Credential:", credential_names, key="scrape_cred")
    credential = credentials_manager.get_credential(selected_cred)
    
    cookies_file = config.BASE_DIR / f"cookies_{selected_cred}.json"
    
    # Check cookies status
    if cookies_file.exists():
        try:
            with open(cookies_file, 'r', encoding='utf-8') as f:
                cookies = json.load(f)
            
            # Show session status
            expiration_dates = []
            for cookie_name, cookie_data in cookies.items():
                if isinstance(cookie_data, dict):
                    exp = cookie_data.get('expiration')
                    if exp and isinstance(exp, (int, float)):
                        expiration_dates.append(exp)
            
            if expiration_dates:
                earliest_exp = min(expiration_dates)
                exp_datetime = datetime.fromtimestamp(earliest_exp)
                now = datetime.now()
                
                if exp_datetime > now:
                    days_until_exp = (exp_datetime - now).days
                    hours_until_exp = ((exp_datetime - now).seconds) // 3600
                    st.success(f"✅ Session Active: {len(cookies)} cookies - Expires: {exp_datetime.strftime('%Y-%m-%d %H:%M')} ({days_until_exp}d {hours_until_exp}h)")
                else:
                    st.error(f"❌ Cookies expired! Expired: {exp_datetime.strftime('%Y-%m-%d %H:%M')}")
            else:
                st.success(f"✅ Cookies loaded: {len(cookies)} cookies available")
        except:
            st.error("❌ Error reading cookies file")
            st.stop()
    else:
        st.warning("⚠️ No cookies found. Please add cookies from 'Credentials' page first.")
        st.stop()
    
    st.markdown("---")
    
    # ============================================================================
    # Smart Course Scraping
    # ============================================================================
    st.markdown("### 🎯 Smart Course Scraping")
    
    scrape_mode = st.radio(
        "Scraping Mode:",
        [
            "📚 Scrape Learning Paths (Recommended)",
            "🎬 Scrape Course Details (Deep Scan)",
            "🔗 Scrape from Custom URL",
            "📄 Scrape All Site Pages"
        ],
        horizontal=False
    )
    
    # Scraping settings
    st.markdown("#### ⚙️ Settings")
    col1, col2, col3 = st.columns(3)
    with col1:
        max_pages = st.number_input("Max Pages:", min_value=1, value=100, step=10)
    with col2:
        delay = st.slider("Delay (seconds):", 0.5, 10.0, value=2.0, step=0.5)
    with col3:
        headless = st.checkbox("Headless Mode", value=True)
    
    # Mode-specific settings
    if scrape_mode == "📚 Scrape Learning Paths (Recommended)":
        st.info("🎯 This will scrape all courses from **https://yanfaa.com/us/learning-paths** and extract course information.")
        learning_paths_url = st.text_input(
            "Learning Paths URL:",
            value="https://yanfaa.com/us/learning-paths",
            help="The URL of the learning paths page"
        )
        
        extract_details = st.checkbox("Extract detailed course information", value=True, help="Follow each course link to get full details")
    
    elif scrape_mode == "🎬 Scrape Course Details (Deep Scan)":
        st.info("🎬 This will deep scan a specific course to extract **lessons, video IDs, subtitles, and materials**.")
        
        # Course slug input
        course_url = st.text_input(
            "Course URL or Slug:",
            value="Basics-of-photoshop",
            help="Enter the course slug (e.g., 'Basics-of-photoshop') or full URL"
        )
        
        # Extract slug from URL if full URL given
        if 'yanfaa.com' in course_url:
            course_slug = course_url.rstrip('/').split('/')[-1]
        else:
            course_slug = course_url.strip()
        
        st.caption(f"📌 Course slug: `{course_slug}`")
        
        col1, col2, col3 = st.columns(3)
        with col1:
            download_subs = st.checkbox("📝 Download Subtitles (VTT)", value=True, help="Download all available subtitle files")
        with col2:
            extract_materials = st.checkbox("📦 Extract Materials Links", value=True, help="Extract PDF and Drive links")
        with col3:
            download_videos = st.checkbox("🎬 Download Videos", value=False, help="Download course videos using yt-dlp (requires enrollment)")
        
    elif scrape_mode == "🔗 Scrape from Custom URL":
        start_url = st.text_input("Start URL:", value=credential.get('base_url', config.BASE_URL))
        
    else:  # Scrape All Site Pages
        start_url = st.text_input("Start URL:", value=credential.get('base_url', config.BASE_URL))
    
    st.markdown("---")
    
    # Start scraping button
    if st.button("🚀 Start Smart Scraping", use_container_width=True, type="primary"):
        progress_container = st.container()
        status_container = st.container()
        results_container = st.container()
        
        with progress_container:
            progress_bar = st.progress(0)
            status_text = st.empty()
        
        def scrape_learning_paths_sync():
            """Smart scraping for learning paths using Yanfaa API"""
            import httpx
            from bs4 import BeautifulSoup
            import re
            import time
            
            courses_found = []
            learning_paths_data = []
            
            # Load cookies and convert to dict for httpx
            cookies_dict = {}
            try:
                with open(cookies_file, 'r', encoding='utf-8') as f:
                    cookies_data = json.load(f)
                for name, data in cookies_data.items():
                    if isinstance(data, dict):
                        cookies_dict[name] = data.get('value', '')
                    else:
                        cookies_dict[name] = str(data)
                print(f"🍪 Loaded {len(cookies_dict)} cookies")
            except Exception as e:
                print(f"Cookie warning: {str(e)}")
            
            # Yanfaa uses API - Extract path name from URL
            # URL format: https://yanfaa.com/us/learning-paths/path_name
            path_name = learning_paths_url.rstrip('/').split('/')[-1]
            api_base = "https://app.yanfaa.com/api"
            
            # If it's the main learning paths page, get all paths first
            if path_name == 'learning-paths' or not path_name:
                api_url = f"{api_base}/learning_paths"
            else:
                api_url = f"{api_base}/learning_paths/{path_name}"
            
            print(f"🔌 Using API: {api_url}")
            
            # Set up headers for API
            headers = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                'Accept': 'application/json, text/plain, */*',
                'Accept-Language': 'en-US,en;q=0.9,ar;q=0.8',
                'Origin': 'https://yanfaa.com',
                'Referer': learning_paths_url,
            }
            
            # Create httpx client with cookies
            with httpx.Client(cookies=cookies_dict, headers=headers, follow_redirects=True, timeout=60.0) as client:
                print(f"🔍 Fetching data from API...")
                
                try:
                    # First, try to get all learning paths
                    all_paths_response = client.get(f"{api_base}/learning_paths")
                    all_paths = []
                    if all_paths_response.status_code == 200:
                        paths_data = all_paths_response.json()
                        # Handle both list and dict responses
                        if isinstance(paths_data, list):
                            all_paths = paths_data
                        elif isinstance(paths_data, dict):
                            all_paths = paths_data.get('learning_paths', paths_data.get('data', []))
                            if not all_paths:
                                all_paths = list(paths_data.values()) if paths_data else []
                        print(f"📚 Found {len(all_paths)} learning paths total")
                    
                    # If specific path requested, get its details
                    if path_name and path_name != 'learning-paths':
                        response = client.get(api_url)
                        response.raise_for_status()
                        response_data = response.json()
                        
                        # Handle API structure: {"data": [{...}]} or direct object
                        if isinstance(response_data, dict):
                            if 'data' in response_data:
                                path_list = response_data['data']
                                path_data = path_list[0] if path_list else {}
                            else:
                                path_data = response_data
                        else:
                            path_data = response_data[0] if response_data else {}
                        
                        print(f"✅ Got learning path: {path_data.get('title', path_name)}")
                        
                        # Extract courses from the learning path
                        courses_in_path = path_data.get('courses', [])
                        print(f"📖 Found {len(courses_in_path)} courses in this path")
                        
                        for i, course in enumerate(courses_in_path[:max_pages]):
                            # Get duration - prefer human readable format
                            duration = course.get('duration_human', '')
                            if not duration:
                                duration_seconds = course.get('duration', 0)
                                if duration_seconds:
                                    hours = duration_seconds // 3600
                                    minutes = (duration_seconds % 3600) // 60
                                    duration = f"{hours}h {minutes}m" if hours > 0 else f"{minutes}m"
                                else:
                                    duration = 'N/A'
                            
                            # Get instructor info - check different possible structures
                            instructor = course.get('instructor', {})
                            if isinstance(instructor, dict):
                                instructor_name = instructor.get('name', 'N/A')
                            else:
                                instructor_name = str(instructor) if instructor else 'N/A'
                            
                            # Get course order from pivot if available
                            pivot = course.get('pivot', {})
                            order = pivot.get('order', i + 1) if isinstance(pivot, dict) else i + 1
                            
                            courses_found.append({
                                'order': order,
                                'title': course.get('title', 'N/A'),
                                'url': f"https://yanfaa.com/us/courses/{course.get('slug', '')}",
                                'description': course.get('desc', course.get('description', ''))[:200] if course.get('desc') or course.get('description') else '',
                                'duration': duration,
                                'instructor': instructor_name,
                                'lessons': str(course.get('lessons_count', 'N/A')),
                                'type': 'course'
                            })
                            print(f"📖 {order}. {course.get('title', 'N/A')[:40]}...")
                    else:
                        # Get all learning paths
                        for i, path in enumerate(all_paths[:max_pages]):
                            courses_found.append({
                                'title': path.get('title', 'N/A'),
                                'url': f"https://yanfaa.com/us/learning-paths/{path.get('slug', '')}",
                                'description': path.get('description', '')[:200] if path.get('description') else '',
                                'duration': 'N/A',
                                'courses_count': str(path.get('courses_count', 0)),
                                'lessons': 'N/A',
                                'type': 'learning-path'
                            })
                            print(f"📚 {i + 1}. {path.get('title', 'N/A')[:40]}...")
                    
                    return courses_found, len(courses_found)
                    
                except httpx.HTTPStatusError as e:
                    raise Exception(f"HTTP Error: {e.response.status_code} - {str(e)}")
                except Exception as e:
                    raise Exception(f"Failed to load data: {str(e)}")
        
        def scrape_course_details_sync(course_slug):
            """Deep scraping for a specific course - extracts lessons, videos, materials"""
            import httpx
            import re
            import time
            
            course_details = {
                'slug': course_slug,
                'title': '',
                'description': '',
                'instructor': '',
                'duration': '',
                'lessons_count': 0,
                'lessons': [],
                'materials': [],
                'subtitles': []
            }
            
            # Load cookies
            cookies_dict = {}
            try:
                with open(cookies_file, 'r', encoding='utf-8') as f:
                    cookies_data = json.load(f)
                for name, data in cookies_data.items():
                    if isinstance(data, dict):
                        cookies_dict[name] = data.get('value', '')
                    else:
                        cookies_dict[name] = str(data)
                print(f"🍪 Loaded {len(cookies_dict)} cookies")
            except Exception as e:
                print(f"Cookie warning: {str(e)}")
            
            headers = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'Accept': 'application/json, text/plain, */*',
                'Origin': 'https://yanfaa.com',
                'Referer': f'https://yanfaa.com/us/single/{course_slug}'
            }
            
            api_url = f"https://app.yanfaa.com/api/course/{course_slug}"
            print(f"🔌 Using API: {api_url}")
            
            with httpx.Client(cookies=cookies_dict, headers=headers, follow_redirects=True, timeout=60.0) as client:
                try:
                    response = client.get(api_url)
                    response.raise_for_status()
                    data = response.json()
                    
                    # Handle API structure
                    course_data = data.get('data', data)
                    if isinstance(course_data, list):
                        course_data = course_data[0] if course_data else {}
                    
                    # Debug: Print available keys
                    print(f"📋 API keys: {list(course_data.keys()) if isinstance(course_data, dict) else 'not a dict'}")
                    
                    # Extract course info
                    course_details['title'] = course_data.get('title', course_slug)
                    course_details['description'] = course_data.get('desc', course_data.get('description', ''))[:500]
                    course_details['duration'] = course_data.get('duration_human', 'N/A')
                    
                    # Instructor
                    instructor = course_data.get('instructor', {})
                    if isinstance(instructor, dict):
                        course_details['instructor'] = instructor.get('name', 'N/A')
                    
                    print(f"✅ Course: {course_details['title']}")
                    
                    # Get course ID for VTT URL
                    course_id_for_vtt = course_data.get('id', 370)
                    
                    # Extract lessons - try multiple possible keys
                    lessons = []
                    
                    # Direct lessons key
                    if course_data.get('lessons'):
                        lessons = course_data['lessons']
                    
                    # Try sections -> lessons
                    if not lessons and course_data.get('sections'):
                        for section in course_data['sections']:
                            if isinstance(section, dict) and section.get('lessons'):
                                lessons.extend(section['lessons'])
                    
                    # Try videos key
                    if not lessons and course_data.get('videos'):
                        lessons = course_data['videos']
                    
                    # Try chapters key
                    if not lessons and course_data.get('chapters'):
                        for chapter in course_data['chapters']:
                            if isinstance(chapter, dict) and chapter.get('lessons'):
                                lessons.extend(chapter['lessons'])
                    
                    # Try fetching from a dedicated lessons endpoint
                    if not lessons:
                        endpoints_to_try = [
                            f"https://app.yanfaa.com/api/course/{course_slug}/lessons",
                            f"https://app.yanfaa.com/api/courses/{course_slug}/lessons",
                            f"https://app.yanfaa.com/api/course/{course_id_for_vtt}/lessons",
                        ]
                        for endpoint in endpoints_to_try:
                            try:
                                print(f"  📥 Trying: {endpoint}")
                                lessons_response = client.get(endpoint)
                                if lessons_response.status_code == 200:
                                    lessons_data = lessons_response.json()
                                    if isinstance(lessons_data, dict):
                                        lessons = lessons_data.get('data', lessons_data.get('lessons', []))
                                    elif isinstance(lessons_data, list):
                                        lessons = lessons_data
                                    if lessons:
                                        print(f"  ✅ Found {len(lessons)} lessons from {endpoint}")
                                        break
                            except Exception as e:
                                print(f"  ❌ {endpoint}: {str(e)[:50]}")
                    
                    course_details['lessons_count'] = len(lessons)
                    print(f"📖 Found {len(lessons)} lessons")
                    
                    for i, lesson in enumerate(lessons):
                        lesson_id = lesson.get('id', '')
                        lesson_title = lesson.get('title', f'Lesson {i+1}')
                        
                        # Duration
                        duration_sec = lesson.get('duration', 0)
                        if duration_sec:
                            mins = duration_sec // 60
                            secs = duration_sec % 60
                            duration_str = f"{mins}:{secs:02d}"
                        else:
                            duration_str = lesson.get('duration_human', 'N/A')
                        
                        # Video ID (Brightcove)
                        video_id = lesson.get('video_id', lesson.get('brightcove_id', ''))
                        
                        # Subtitle URL pattern: /video/25/{course_id}/{lesson_id}.vtt
                        subtitle_url = f"https://yanfaa.s3.eu-west-1.amazonaws.com/video/25/{course_id_for_vtt}/{lesson_id}.vtt"
                        
                        # Materials for this lesson
                        lesson_materials = lesson.get('material', [])
                        
                        lesson_info = {
                            'order': i + 1,
                            'id': lesson_id,
                            'title': lesson_title,
                            'duration': duration_str,
                            'video_id': str(video_id) if video_id else 'N/A',
                            'subtitle_url': subtitle_url if lesson_id else 'N/A',
                            'materials': lesson_materials,
                            'is_free': lesson.get('free', False)
                        }
                        
                        course_details['lessons'].append(lesson_info)
                        
                        # Collect materials
                        for mat in lesson_materials:
                            course_details['materials'].append({
                                'lesson': lesson_title,
                                'lesson_id': lesson_id,
                                'name': mat.get('name', 'Material'),
                                'type': mat.get('type', 'unknown'),
                                'link': mat.get('link', '')
                            })
                        
                        print(f"  📖 {i+1}. {lesson_title[:40]}... (Video: {video_id or 'N/A'})")
                    
                    # Try to validate/download subtitles
                    print(f"\n🔍 Checking subtitles...")
                    for lesson in course_details['lessons'][:5]:  # Check first 5
                        if lesson['subtitle_url'] != 'N/A':
                            try:
                                sub_response = client.get(lesson['subtitle_url'])
                                if sub_response.status_code == 200 and 'WEBVTT' in sub_response.text:
                                    course_details['subtitles'].append({
                                        'lesson': lesson['title'],
                                        'url': lesson['subtitle_url'],
                                        'available': True
                                    })
                                    print(f"  ✅ Subtitle found: {lesson['title'][:30]}...")
                            except:
                                pass
                    
                    return course_details
                    
                except httpx.HTTPStatusError as e:
                    raise Exception(f"HTTP Error: {e.response.status_code}")
                except Exception as e:
                    raise Exception(f"Failed to load course: {str(e)}")
        
        def download_subtitles_sync(course_details, output_dir):
            """Download all available VTT subtitle files"""
            import httpx
            import re
            
            downloaded = []
            
            cookies_dict = {}
            try:
                with open(cookies_file, 'r', encoding='utf-8') as f:
                    cookies_data = json.load(f)
                for name, data in cookies_data.items():
                    if isinstance(data, dict):
                        cookies_dict[name] = data.get('value', '')
                    else:
                        cookies_dict[name] = str(data)
            except:
                pass
            
            headers = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            }
            
            output_path = Path(output_dir)
            output_path.mkdir(parents=True, exist_ok=True)
            
            with httpx.Client(cookies=cookies_dict, headers=headers, timeout=30.0) as client:
                for lesson in course_details.get('lessons', []):
                    url = lesson.get('subtitle_url', '')
                    if url and url != 'N/A':
                        try:
                            response = client.get(url)
                            if response.status_code == 200:
                                # Clean filename
                                safe_title = re.sub(r'[^\w\s-]', '', lesson.get('title', 'lesson'))[:50]
                                filename = f"{lesson.get('order', 0):02d}_{safe_title}.vtt"
                                filepath = output_path / filename
                                filepath.write_text(response.text, encoding='utf-8')
                                downloaded.append(str(filepath))
                                print(f"✅ Downloaded: {filename}")
                        except Exception as e:
                            print(f"❌ Failed: {lesson.get('title', '')[:30]} - {str(e)}")
            
            return downloaded
        
        def download_videos_sync(course_slug, output_dir):
            """Download course videos using yt-dlp"""
            import subprocess
            import re
            
            downloaded = []
            errors = []
            
            output_path = Path(output_dir)
            output_path.mkdir(parents=True, exist_ok=True)
            
            # Create Netscape cookies file for yt-dlp
            netscape_cookies_file = output_path / "cookies.txt"
            try:
                with open(cookies_file, 'r', encoding='utf-8') as f:
                    cookies_data = json.load(f)
                
                with open(netscape_cookies_file, 'w', encoding='utf-8') as f:
                    f.write("# Netscape HTTP Cookie File\n")
                    f.write("# https://curl.haxx.se/rfc/cookie_spec.html\n")
                    f.write("# This is a generated file! Do not edit.\n\n")
                    
                    for name, data in cookies_data.items():
                        if isinstance(data, dict):
                            domain = data.get('domain', '.yanfaa.com')
                            path = data.get('path', '/')
                            secure = 'TRUE' if data.get('secure', False) else 'FALSE'
                            expiry = str(int(data.get('expiration', 0)))
                            value = data.get('value', '')
                        else:
                            domain = '.yanfaa.com'
                            path = '/'
                            secure = 'FALSE'
                            expiry = '0'
                            value = str(data)
                        
                        # Netscape format: domain\tflag\tpath\tsecure\texpiry\tname\tvalue
                        flag = 'TRUE' if domain.startswith('.') else 'FALSE'
                        f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")
                
                print(f"🍪 Created Netscape cookies file: {netscape_cookies_file}")
            except Exception as e:
                print(f"⚠️ Cookie file warning: {str(e)}")
            
            # Course URL
            course_url = f"https://yanfaa.com/us/single/{course_slug}"
            
            # yt-dlp command (using python -m for Windows compatibility)
            cmd = [
                sys.executable, '-m', 'yt_dlp',
                '--cookies', str(netscape_cookies_file),
                '-o', str(output_path / '%(title)s.%(ext)s'),
                '--write-subs',
                '--sub-langs', 'all',
                '--embed-subs',
                '--no-check-certificate',
                '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                course_url
            ]
            
            print(f"🎬 Starting video download: {course_url}")
            print(f"📁 Output: {output_path}")
            
            try:
                # Run yt-dlp
                result = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    timeout=600  # 10 minute timeout
                )
                
                if result.returncode == 0:
                    print(f"✅ Video download completed!")
                    # Find downloaded files
                    for f in output_path.glob('*.mp4'):
                        downloaded.append(str(f))
                    for f in output_path.glob('*.mkv'):
                        downloaded.append(str(f))
                    for f in output_path.glob('*.webm'):
                        downloaded.append(str(f))
                else:
                    error_msg = result.stderr[:500] if result.stderr else "Unknown error"
                    print(f"❌ yt-dlp error: {error_msg}")
                    errors.append(error_msg)
                    
            except subprocess.TimeoutExpired:
                errors.append("Download timed out after 10 minutes")
                print("❌ Download timed out")
            except FileNotFoundError:
                errors.append("yt-dlp not found. Install it with: pip install yt-dlp")
                print("❌ yt-dlp not found")
            except Exception as e:
                errors.append(str(e))
                print(f"❌ Error: {str(e)}")
            
            return downloaded, errors
        
        async def run_standard_scraping(url):
            """Standard site scraping"""
            config.HEADLESS = headless
            config.DELAY_BETWEEN_REQUESTS = delay
            
            auth = YanfaaAuth(
                email=credential.get('username', credential.get('email', '')),
                password=credential['password'],
                cookies_file=str(cookies_file)
            )
            
            async with YanfaaScraper(auth) as scraper:
                status_text.info(f"🔄 Starting to scrape from: {url}")
                results = await scraper.scrape_site(start_url=url, max_pages=max_pages)
                scraper.save_results()
                return scraper
        
        def run_async_in_thread(coro):
            """Run async code in a separate thread with proper Windows event loop"""
            import threading
            result = [None, None]
            
            def thread_target():
                # Create new event loop for this thread
                if sys.platform == 'win32':
                    # Use ProactorEventLoop for Windows (required for Playwright subprocess)
                    loop = asyncio.ProactorEventLoop()
                else:
                    loop = asyncio.new_event_loop()
                asyncio.set_event_loop(loop)
                try:
                    result[0] = loop.run_until_complete(coro)
                except Exception as e:
                    result[1] = e
                finally:
                    loop.close()
            
            thread = threading.Thread(target=thread_target)
            thread.start()
            thread.join()
            
            if result[1]:
                raise result[1]
            return result[0]
        
        try:
            if scrape_mode == "📚 Scrape Learning Paths (Recommended)":
                status_text.info("🔄 Starting smart scraping...")
                courses, total_links = scrape_learning_paths_sync()
                progress_bar.progress(1.0)
                
                status_text.success(f"✅ Scraping completed!")
                
                with results_container:
                    st.markdown("### 📊 Courses Found")
                    
                    col1, col2, col3 = st.columns(3)
                    with col1:
                        st.metric("📚 Courses Found", len(courses))
                    with col2:
                        st.metric("🔗 Total Links", total_links)
                    with col3:
                        st.metric("✅ Scraped", len([c for c in courses if c.get('title') != 'Error']))
                    
                    if courses:
                        # Convert to DataFrame and display
                        df = pd.DataFrame(courses)
                        st.dataframe(df, use_container_width=True, height=400)
                        
                        # Save results
                        results_file = config.OUTPUT_DIR / "courses_found.json"
                        with open(results_file, 'w', encoding='utf-8') as f:
                            json.dump(courses, f, indent=2, ensure_ascii=False)
                        
                        st.success(f"💾 Results saved to: {results_file}")
                        
                        # Download button
                        csv_data = df.to_csv(index=False).encode('utf-8')
                        st.download_button(
                            label="📥 Download as CSV",
                            data=csv_data,
                            file_name="yanfaa_courses.csv",
                            mime="text/csv"
                        )
                    
                    st.balloons()
            
            elif scrape_mode == "🎬 Scrape Course Details (Deep Scan)":
                status_text.info(f"🔄 Deep scanning course: {course_slug}...")
                progress_bar.progress(0.2)
                
                # Scrape course details
                course_details = scrape_course_details_sync(course_slug)
                progress_bar.progress(0.6)
                
                # Download subtitles if requested
                subtitles_downloaded = []
                if download_subs:
                    status_text.info("📝 Downloading subtitles...")
                    subs_dir = config.OUTPUT_DIR / course_slug / "subtitles"
                    subtitles_downloaded = download_subtitles_sync(course_details, str(subs_dir))
                    progress_bar.progress(0.7)
                
                # Download videos if requested
                videos_downloaded = []
                video_errors = []
                if download_videos:
                    status_text.info("🎬 Downloading videos (this may take a while)...")
                    videos_dir = config.OUTPUT_DIR / course_slug / "videos"
                    videos_downloaded, video_errors = download_videos_sync(course_slug, str(videos_dir))
                    progress_bar.progress(0.95)
                
                progress_bar.progress(1.0)
                status_text.success(f"✅ Deep scan completed!")
                
                with results_container:
                    st.markdown(f"### 🎬 Course: {course_details.get('title', course_slug)}")
                    
                    # Course info metrics
                    col1, col2, col3, col4, col5 = st.columns(5)
                    with col1:
                        st.metric("📖 Lessons", course_details.get('lessons_count', 0))
                    with col2:
                        st.metric("⏱️ Duration", course_details.get('duration', 'N/A'))
                    with col3:
                        st.metric("📝 Subtitles", len(subtitles_downloaded))
                    with col4:
                        st.metric("🎬 Videos", len(videos_downloaded))
                    with col5:
                        st.metric("📦 Materials", len(course_details.get('materials', [])))
                    
                    # Show video download status
                    if download_videos:
                        if videos_downloaded:
                            st.success(f"✅ Downloaded {len(videos_downloaded)} video(s)")
                            for vid in videos_downloaded:
                                st.caption(f"📁 {vid}")
                        elif video_errors:
                            st.warning("⚠️ Video download issues:")
                            for err in video_errors:
                                st.caption(f"❌ {err[:100]}...")
                    
                    st.markdown(f"**Instructor:** {course_details.get('instructor', 'N/A')}")
                    
                    if course_details.get('description'):
                        with st.expander("📄 Description"):
                            st.write(course_details['description'])
                    
                    # Lessons table
                    st.markdown("#### 📖 Lessons")
                    lessons = course_details.get('lessons', [])
                    if lessons:
                        lessons_df = pd.DataFrame([{
                            'Order': l.get('order', 0),
                            'Title': l.get('title', ''),
                            'Duration': l.get('duration', 'N/A'),
                            'Video ID': l.get('video_id', 'N/A'),
                            'Free': '✅' if l.get('is_free') else '❌',
                            'Materials': len(l.get('materials', []))
                        } for l in lessons])
                        st.dataframe(lessons_df, use_container_width=True, height=300)
                    
                    # Materials section
                    materials = course_details.get('materials', [])
                    if materials and extract_materials:
                        st.markdown("#### 📦 Materials & Resources")
                        materials_df = pd.DataFrame([{
                            'Lesson': m.get('lesson', ''),
                            'Name': m.get('name', ''),
                            'Type': m.get('type', ''),
                            'Link': m.get('link', '')
                        } for m in materials])
                        st.dataframe(materials_df, use_container_width=True, height=200)
                        
                        # Materials links text
                        st.markdown("##### 🔗 Download Links")
                        for mat in materials:
                            if mat.get('link'):
                                st.markdown(f"- **{mat.get('name', 'Material')}**: [{mat.get('link')[:50]}...]({mat.get('link')})")
                    
                    # Save results
                    course_dir = config.OUTPUT_DIR / course_slug
                    course_dir.mkdir(parents=True, exist_ok=True)
                    
                    results_file = course_dir / "course_details.json"
                    with open(results_file, 'w', encoding='utf-8') as f:
                        json.dump(course_details, f, indent=2, ensure_ascii=False)
                    
                    st.success(f"💾 Results saved to: {results_file}")
                    
                    # Download buttons
                    st.markdown("---")
                    st.markdown("#### 📥 Download")
                    
                    col1, col2, col3 = st.columns(3)
                    with col1:
                        # JSON download
                        json_data = json.dumps(course_details, indent=2, ensure_ascii=False).encode('utf-8')
                        st.download_button(
                            label="📥 Full JSON",
                            data=json_data,
                            file_name=f"{course_slug}_details.json",
                            mime="application/json"
                        )
                    
                    with col2:
                        # Lessons CSV
                        if lessons:
                            lessons_csv = lessons_df.to_csv(index=False).encode('utf-8')
                            st.download_button(
                                label="📥 Lessons CSV",
                                data=lessons_csv,
                                file_name=f"{course_slug}_lessons.csv",
                                mime="text/csv"
                            )
                    
                    with col3:
                        # Materials links file
                        if materials:
                            links_text = "\n".join([
                                f"[{m.get('lesson', '')}] {m.get('name', '')}: {m.get('link', '')}"
                                for m in materials if m.get('link')
                            ])
                            st.download_button(
                                label="📥 Material Links",
                                data=links_text.encode('utf-8'),
                                file_name=f"{course_slug}_materials.txt",
                                mime="text/plain"
                            )
                    
                    st.balloons()
            
            else:
                # Standard scraping
                if scrape_mode == "🔗 Scrape from Custom URL":
                    scraper = run_async_in_thread(run_standard_scraping(start_url))
                else:
                    scraper = run_async_in_thread(run_standard_scraping(start_url))
                
                if scraper:
                    successful = len([r for r in scraper.scraped_data if r.get("success")])
                    failed = len([r for r in scraper.scraped_data if not r.get("success")])
                    
                    progress_bar.progress(1.0)
                    status_text.success(f"✅ Scraping completed!")
                    
                    with results_container:
                        st.markdown("### 📊 Scraping Results")
                        col1, col2, col3 = st.columns(3)
                        with col1:
                            st.metric("✅ Successful", successful)
                        with col2:
                            st.metric("❌ Failed", failed)
                        with col3:
                            st.metric("📄 Total", len(scraper.scraped_data))
                        
                        st.success("💾 Results saved in output/ folder")
                        st.balloons()
        
        except Exception as e:
            st.error(f"❌ Error: {str(e)}")
            import traceback
            with st.expander("Error Details"):
                st.code(traceback.format_exc())
